name: Question or Help
description: Ask for help or general questions
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: "Ask your question here..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide context about what you're trying to accomplish.
      placeholder: "I'm trying to..."
    validations:
      required: false
  - type: textarea
    id: what-tried
    attributes:
      label: What have you tried?
      description: What have you already attempted to solve this?
      placeholder: "I've tried..."
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please provide your configuration file content if relevant
      placeholder: |
        ```yaml
        # .github/assign_reviewers.yml
        components:
          src/:
            - user1
        ```
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - Action version: v1.0.0
        - Repository type: Public/Private
        - GitHub plan: Free/Pro/Team/Enterprise
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about your question here.
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0